// app/_styles.ts
import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  scrollContainer: {
    backgroundColor: '#FECACA',
    flexGrow: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  container: {
    padding: 35,
    gap: 25,
    maxWidth: 900,
    alignSelf: 'center',
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    marginVertical: 25,
    ...(Platform.OS === 'web' ? { boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.15)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 5,
    }),
  },
  header: {
    fontSize: 40,
    fontFamily: 'Georgia',
    fontWeight: 'bold',
    color: '#D32F2F',
    textAlign: 'center',
    ...(Platform.OS === 'web' ? { textShadow: '1px 1px 3px rgba(0, 0, 0, 0.2)' } : {}),
    marginBottom: 10,
  },
  trustSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 15,
  },
  trustText: {
    fontSize: 14,
    fontFamily: 'Arial',
    color: '#4A4A4A',
    fontWeight: '500',
  },
  inputSection: {
    gap: 20,
    backgroundColor: 'rgba(255, 247, 247, 0.95)',
    padding: 25,
    borderRadius: 15,
    ...(Platform.OS === 'web' ? { boxShadow: '0px 0px 5px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
    }),
  },
  label: {
    fontSize: 20,
    fontFamily: 'Arial',
    color: '#4A4A4A',
    fontWeight: '600',
    letterSpacing: 0.5,
    marginBottom: 5,
  },
  input: {
    borderWidth: 0,
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    fontFamily: 'Arial',
    backgroundColor: '#FFFFFF',
    color: '#333',
    ...(Platform.OS === 'web' ? { boxShadow: '0px 0px 4px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    }),
  },
  suggestionRow: {
    flexDirection: 'row',
    gap: 15,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  searchRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginBottom: 10,
  },
  picker: {
    flex: 1,
    height: 50,
    backgroundColor: '#FFF',
    borderRadius: 12,
    borderColor: '#E0E0E0',
    borderWidth: 1,
    fontFamily: 'Arial',
  },
  spinnerContainer: {
    marginVertical: 20,
    alignItems: 'center',
  },
  spinnerText: {
    fontSize: 16,
    fontFamily: 'Arial',
    color: '#FF6B6B',
    marginTop: 10,
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 20,
    justifyContent: 'center',
    marginTop: 20,
    flexWrap: 'wrap',
  },
  recipeContainer: {
    marginTop: 30,
    padding: 30,
    backgroundColor: '#FFF',
    borderRadius: 15,
    borderLeftWidth: 5,
    borderLeftColor: '#FF6B6B',
    ...(Platform.OS === 'web' ? { boxShadow: '0px 0px 8px rgba(0, 0, 0, 0.2)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
    }),
  },
  recipeCard: {
    borderWidth: 2,
    borderColor: '#FF6B6B',
    backgroundColor: '#FFF5F5',
    ...(Platform.OS === 'web' ? { boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.3)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    }),
  },
  recipeButtons: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 25,
    flexWrap: 'wrap',
  },
  errorContainer: {
    marginTop: 20,
    padding: 20,
    backgroundColor: '#FFF5F5',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF3B30',
    alignItems: 'center',
    ...(Platform.OS === 'web' ? { boxShadow: '0px 0px 5px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
    }),
  },
  title: {
    fontSize: 32,
    fontFamily: 'Georgia',
    fontWeight: '700',
    color: '#D32F2F',
    marginBottom: 20,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 24,
    fontFamily: 'Arial',
    fontWeight: '600',
    color: '#4A4A4A',
    marginTop: 20,
    marginBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#FF6B6B',
    paddingBottom: 6,
  },
  listItem: {
    fontSize: 16,
    fontFamily: 'Arial',
    color: '#555',
    lineHeight: 28,
    marginVertical: 5,
  },
  nutrition: {
    fontSize: 15,
    fontFamily: 'Arial',
    color: '#777',
    lineHeight: 26,
    fontStyle: 'italic',
    marginVertical: 3,
  },
  detail: {
    fontSize: 15,
    fontFamily: 'Arial',
    color: '#555',
    lineHeight: 26,
    marginVertical: 3,
  },
  favorites: {
    marginTop: 30,
    padding: 30,
    backgroundColor: '#FFF',
    borderRadius: 15,
    borderLeftWidth: 5,
    borderLeftColor: '#4ECDC4',
    ...(Platform.OS === 'web' ? { boxShadow: '0px 0px 5px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
    }),
  },
  favItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    ...(Platform.OS === 'web' ? { transition: 'background-color 0.2s' } : {}),
  },
  favItem: {
    fontSize: 16,
    fontFamily: 'Arial',
    color: '#555',
    lineHeight: 28,
    marginVertical: 5,
  },
  noFavorites: {
    fontSize: 16,
    fontFamily: 'Arial',
    color: '#777',
    textAlign: 'center',
    marginVertical: 10,
  },
  error: {
    fontSize: 16,
    fontFamily: 'Arial',
    color: '#FF3B30',
    textAlign: 'center',
    marginBottom: 10,
    fontWeight: '500',
  },
  copyButton: {
    backgroundColor: '#007AFF',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignItems: 'center',
  },
  copyButtonText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Arial',
  },
  affiliateSection: {
    marginTop: 30,
    padding: 20,
    backgroundColor: '#FFF',
    borderRadius: 15,
    ...(Platform.OS === 'web' ? { boxShadow: '0px 0px 5px rgba(0, 0, 0, 0.1)' } : {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
    }),
  },
  affiliateHeader: {
    fontSize: 24,
    fontFamily: 'Arial',
    fontWeight: '600',
    color: '#4A4A4A',
    marginBottom: 15,
    textAlign: 'center',
  },
  affiliateContainer: {
    marginVertical: 15,
    alignItems: 'center',
  },
  affiliateLinkLarge: {
    fontSize: 20,
    fontFamily: 'Arial',
    color: '#1DA1F2',
    textDecorationLine: 'underline',
    marginBottom: 10,
  },
  affiliateImages: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
  },
  affiliateImageLarge: {
    width: 150,
    height: 150,
    marginBottom: 10,
  },
  affiliateDisclaimer: {
    fontSize: 14,
    fontFamily: 'Arial',
    color: '#777',
    textAlign: 'center',
    marginTop: 15,
    fontStyle: 'italic',
  },
  footer: {
    marginTop: 20,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    fontSize: 12,
    fontFamily: 'Arial',
    color: '#777',
  },
  footerLink: {
    color: '#1DA1F2',
    textDecorationLine: 'underline',
  },
});